[package]
name        = "bevy_toolbox"
version     = "0.2.0"
edition     = "2021"
license     = "MIT"
repository  = "https://github.com/tnthung/bevy_toolbox"
description = "Spawn macro for bevy_toolbox"

[dependencies]
bevy_toolbox_spawn = "0.3.0"
