[package]
name    = "bevy_toolbox_spawn"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn         = { version = "2.0.100", features = ["full"] }
quote       = "1.0.40"
proc-macro2 = "1.0.94"
